import{a as v,S as E,i as n}from"./assets/vendor-64b55ca9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const c of e.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function r(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function i(t){if(t.ep)return;t.ep=!0;const e=r(t);fetch(t.href,e)}})();const R="42324270-89622daef349524aeb531ebd1",S="https://pixabay.com/api/",$="image_type=photo&orientation=horizontal&safesearch=true&per_page=15";async function m(s,o,r){const i=`${S}?key=${R}&q=${s}&${$}&page=${o}`;try{return(await v.get(i)).data}catch{r.error({title:"Error",message:"Error while fetching images",position:"topRight",timeout:2500})}}function u(s){const o=document.querySelector(".gallery");function r(e){const c=e.webformatURL,p=e.largeImageURL,f=e.tags,y=e.likes,w=e.views,L=e.comments,b=e.downloads;return`<div class="card">
            <a href='${p}' class="large-image-link">
              <img class="image" src='${c}' alt="${f}">
              <div class="info">
                <p class="info-item"><span class="info-header">Likes</span><br>${y}</p>
                <p class="info-item"><span class="info-header">Views</span><br>${w}</p>
                <p class="info-item"><span class="info-header">Comments</span><br>${L}</p>
                <p class="info-item"><span class="info-header">Downloads</span><br>${b}</p>
              </div>
            </a>
          </div>`}let i="";s.forEach(e=>{i+=r(e)}),o.insertAdjacentHTML("beforeend",i),new E(".large-image-link").refresh()}const q=document.querySelector(".submitForm"),h=document.querySelector(".searchInput"),a=document.querySelector(".loadMoreBtn"),d=document.querySelector(".loader"),g=document.querySelector(".gallery");let l=1;q.addEventListener("submit",async s=>{s.preventDefault();const o=h.value.trim();if(o===""){n.show({position:"topRight",timeout:2e3,message:"Please, enter the word!",close:!1,messageColor:"white",backgroundColor:"grey"});return}try{d.classList.remove("hidden"),g.innerHTML="",l=1;const r=await m(o,l,n);r.hits.length===0?(a.classList.add("hidden"),n.show({position:"topRight",timeout:3500,message:"Sorry, there are no images matching your search query. Please try again!",close:!1,messageColor:"white",backgroundColor:"green"})):(u(r.hits),r.hits.length>=15?a.classList.remove("hidden"):a.classList.add("hidden"))}catch{n.error({title:"Error",message:"Error while rendering images",position:"topRight",timeout:2500})}finally{d.classList.add("hidden")}});a.addEventListener("click",async()=>{a.classList.remove("hidden");let s,o;l+=1;const r=h.value.trim();try{s=await m(r,l,n),o=s.totalHits,u(s.hits),C()}catch{n.error({title:"Error",message:"Error while rendering images",position:"topRight",timeout:2500})}finally{s&&l*15>=s.totalHits?(a.classList.add("hidden"),n.show({position:"topRight",timeout:3500,message:"We're sorry, but you've reached the end of search results.",close:!1,messageColor:"white",backgroundColor:"green"})):a.classList.remove("hidden")}});function C(){const s=g.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
